config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  devise_for :users
  root to: "homes#top"
  get'home/about', to: 'homes#about', as: 'about'

  resources :taberus
  resources :users, only: [:show, :edit, :update, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/taberu.rb
class Taberu < ApplicationRecord
  has_one_attached :image
  belongs_to :user  

  validates :body, length: { maximum: 200}

  validates :title, presence: true
  validates :body, presence: true

 def get_image
    unless image.attached?
      file_path = Rails.root.join
      image.attach(io: file.open(file_path), filename:'default-image.jpg',content_type: 'image/jpeg')
    end
    image
  end
end  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_one_attached :profile_image      
   has_many :taberus, :dependent => :destroy  #投稿したデータも削除する

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20}
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
       file_path = Rails.root.join('app/assets/images/no_image.jpg')
       profile_image.attach(io: File.open(file_path), filename: 'default-image-jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # top about アクションを除いてauthenticate_user（ログイン）チェックをする
  before_action :authenticate_user!, except: [:top, :about]
  # devise_controllerアクションだった場合configure_permitted_parameters実行（サインアップ時にネームカラムを受け取る）
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    taberus_path(current_user)
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/taberus_controller.rb
class TaberusController < ApplicationController
  def new
    @taberu = Taberus.new  
  end

  def edit
    @taberu = Taberu.find(params[:id])
    if @taberu.user == current_user
      render "edit"
    else
      redirect_to taberus_path
    end
  end




  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @taberu = Taberu.new(taberu_params)
    @taberu.user_id = current_user.id
    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @taberu.save
      # 3. フラッシュメッセージを定義し、詳細画面へリダイレクト
      flash[:notice] = "You have creatad taberu successfully"
      redirect_to taberu_path(@taberu.id)
    else
      @user = current_user
      @taberus = Taberu.all
      #byebug
      render 'index'
    end
  end

  def index
    @users = User.all
    if current_user
      @user = current_user
    end
      @taberus = Taberu.all
      @taberu = Taberu.new
  end

  def show
    @newtaberu = Taberu.new
    #詳細ページを表示する時
    @taberu = Taberu.find(params[:id])
    @user = @taberu.user
  end

  def update
    @taberu = Taberu.find(params[:id])
    @taberu.assign_attributes(taberu_params)
    
    
     if @taberu.save
       flash[:notice] = "Taberu was successfully updated"
       redirect_to taberu_path(@taberu.id)
     else
       flash.now[:alert] = @taberu.errors.full_messages.join
       render :edit
      end 
  end

  def destroy
    @taberu = Taberu.find(params[:id])
    if @taberu.destroy
       flash[:notice]="Taberu was successfully destroyed"
       redirect_to taberus_path
    end
  end

  private
  def taberu_params
    params.require(:taberu).permit(:title, :body)
 end

 def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  def new
    @user = @User.new
  end

  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @user = User.new(user_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @user.save
      # 3. フラッシュメッセージを定義し、詳細画面へリダイレクト
      flash[:notice] = "ユーザー登録に成功しました。"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "ユーザー登録に失敗しました。"
      render :new
    end
  end

  def index
    if current_user
      @user = current_user
    end
      @users = User.all
      @taberus = Taberu.all
      @newtaberu = Taberu.new
  end




  def show
    @user = User.find(params[:id])
    @taberu = Taberu.new
    @taberus = Taberu.where(user_id: @user.id)
    @newtaberu = Taberu.new
  end
  
  def edit
  end

  def destroy
    @user = User.find(params[:id]) #追加
    @user.destroy  # データ（レコード）を削除
    flash[:notice] = "ユーザーを削除しました。" #追加
    redirect_to '/users'  # 投稿一覧画面へリダイレクト
  end

  def update
    if  @user.update(user_params)
      flash[:notice] = "You have update user successfully"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/taberus_helper.rb
module TaberusHelper
end

app/views/homes/about.html.erb
<div class="container-fluid mt-5">
  <div class="header row">
    <div class="mx-auto">
      <div class="col">
        <h2>welcome to <i class="fas fa-nanitaberu"></i>Nanitaberu !!</h2>

      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt-5">
  <div class="footer row">
    <div class="mx-auto">
      
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<% if notice %>
  <p class="alert alert-success bg-white"><%= notice %></p>
<% end %>

<% if user_signed_in? %>
  <div class="container-fluid mt-5">
    <div class="header row">
      <div class="mx-auto">
        <div class="col">
          <h1>Welcome to <i class="fa-brands fa-apple"></i> Nanitaberus!!</h1>
          <p>In <i class="fa-brands fa-apple"></i> Nanitaberus,</p>
          <p>美味しい料理を共有出来る仲間を増やそう！</p>
        </div>
        <div class="btn-box col-10 mx-auto mt-5">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign-in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign-up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container-fluid mt-5">
    <div class="header row">
      <div class="mx-auto">
        <div class="col">
          <h2>Welcome to <i class="fa-brands fa-apple"></i> Nanitaberus!!</h2>
          <p>In <i class="fa-brands fa-apple"></i> Nanitaberus,</p>
          <p>美味しい料理を共有出来る仲間を増やそう！</p>
        </div>
        <div class="btn-box col-10 mx-auto mt-5">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign-in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign-up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render 'taberus/footer' %>

app/views/layouts/_error.html.erb
<%= content_for(:error_messages) do %>
  <% if model.errors.any? %>
    <p id="notice"></p>
    <div class="container px-5 px-sm0">
      <div id="error_explanation">
        <h2><%= pluralize(model.errors.count,"error") %> prohibited this taberu from being saved:</h2>
        <ul>
        <% model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title>Nanitaberu</title>
     <meta name="viewport" content="width=device-width,initial-scale=1">
     <%= csrf_meta_tags %>
     <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width,initial-scale=1 maximum-scale=1">
     <script src="https://kit.fontawesome.com/4c018c7cce.js" crossorigin="anonymous"></script>
     <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    
  <body>  
  <header>
   <div class="container-fluid bg-secondary">
     <div class="row px-5 py-4"
       <div class="col-3 d-flex justify-content-strat">
        <%= link_to "Nanitaberu", root_path, style: 'color: white;' %>
       </div>

       <div class="col-6 offset-3 d-flex justify-content-end">
         <div class="d-flex">
            <% if user_signed_in? %>

            <%= link_to user_path(current_user.id), class: 'text-white mr-3' do %>
              <i class="fa-solid fa-house"></i>Home
            <% end %>
            
            <%= link_to users_path, class: 'text-white mr-3' do %>
              <i class="fa-solid fa-users"></i>Users
            <% end %>
            <%= link_to taberus_path, class: 'text-white mr-3' do %>
              <i class="fa-brands fa-apple"></i>Taberus
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'text-white mr-3' do %>
              <i class="fa-solid fa-right-from-bracket"></i>Log out
            <% end %>
          <% else %>
            <%= link_to root_path, class: 'text-white mr-3' do %>
              <i class="fa-solid fa-house"></i>Home
            <% end %>
            <%= link_to about_path, class: 'text-white mr-3' do %>
              <i class="fa-solid fa-link"></i>About
            <% end %>
            <%= link_to new_user_registration_path, class: 'text-white mr-3' do %>
              <i class="fa-solid fa-user-plus"></i>Sign up
            <% end %>
              <%= link_to new_user_session_path, class: 'text-white' do %>
              <i class="fa-solid fa-right-to-bracket"></i>Log in
            <% end %>
         <% end %>
       </div>
     </div>
   </div>
   </div>
   </header>
    <main>
      <% if notice.present? %>
        <div class="alert alert-success bg-white">
          <%= notice %>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="alert alert-danger bg-white">
          <%= alert %>
        </div>
      <% end %>
      <%= yield(:error_messages) %>
      <%= yield %>
    </main>
    <footer style="text-align: center; margin-top: 50px;">
      <p>CopyRight Taberuno_suki.inc</p>
    </footer>
  </body>
</html>

app/views/taberus/_footer.html.erb
<div class="container-fluid mt-5">
  <div class="footer row">
     <div class="mx-auto">
        
     </div>
  </div>
</div>

app/views/taberus/_taberu.html.erb
<h1>User info</h1>
    <% if @user.present? %>
      <%= image_tag @user.get_profile_image(100, 100) %>
      <hr>
        <p>name: <%= @user.name %></p>
      <% if @user.introduction.present? %>
      <hr>
        <p>introduction: <%= @user.introduction %></p>
      <% else %>
        <p>introduction: 自己紹介文はありません</p>
      <% end %>
      <% else %>
        <p>ユーザー情報が見つかりません</p>
    <% end %>

    <% if current_user && @user.present? %>
      <div class="col mt-5">
        <p><%= link_to edit_user_path(@user), class: "btn btn-outline-dark btn-block" do %>
           <i class="fa-solid fa-user-gear"></i>
        <% end %></p>
      </div>
    <% end %>

    <% @newtaberu ||= Taberu.new %>

  <h1>New taberu</h1>
  <%= form_with model: @newtaberu do |f| %>
    <div class="field">
         <!-- f.label :title 入力する事でcode内では小文字でもサイト上では大文字になる。 -->
      <%= f.label :title %><br>
         <!--小さい文字入力出来るフィールドが出来る。-->
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :opinion %><br>
      <%= f.text_area :body %>
    </div>
    <div class="row ml-0">
      <%= f.submit 'Create Taberu', class: "btn btn-success" %>
    </div>
  <% end %>    

app/views/taberus/edit.html.erb
<h1>Editing Taberu</h1>

<%= form_with model: @taberu, local: true do |f| %>
  <%= render "layouts/error", model: f.object %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :opinion %><br>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit 'Update Taberu',  class: "btn btn-success"   %>
  </div>
   <%= link_to "Show", taberu_path(@taberu.id) %>
   |
   <%= link_to "Back", taberus_path(@taberu.id) %>
<% end %>

app/views/taberus/index.html.erb
<%= render "layouts/error", model: @taberu %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
       <%= render 'taberus/taberu', taberus: @taberus, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
       <h1>Taberus</h1>
          <table class="table">
            <thead>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </thead>
            <tbody>
            <% @taberus.each do |taberu| %>
              <tr>
                <td>
                  <%= link_to user_path(taberu.user) do %>
                    <%= image_tag taberu.user.get_profile_image(100, 100) %>
                  <% end %>
                </td>
                <td><%= link_to taberu.title, taberu_path(taberu) %></td>
                <td><%= taberu.body %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <%= render 'taberus/footer' %>

app/views/taberus/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: @taberu do |f| %>
  <%= render "layouts/error", model: f.object %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
	
  <h4>本文</h4>
  <%= f.text_area :body %>
	
  <%= f.submit '投稿' %>
<% end %>

app/views/taberus/show.html.erb
<div class="container" >
  <div class="row">
      <div class="col-md-3">
        <%= render 'taberus/taberu', taberus: @taberus, user: @user %>
      </div>
       <div class="col-md-8 offset-md-1">
         <h1>Taberu detail</h1>
         <table class="table">
         </tbody>
           <tr>
             <td>
                 <%= link_to user_path(@taberu.user) do %>
                   <%= image_tag @taberu.user.get_profile_image(100, 100) %><br>
                   <%= @taberu.user.name %>
                 <% end %>
             </td>
             <td><%= link_to @taberu.title, taberu_path(@taberu) %></td>
             <td><%= @taberu.body %></td>
             <% if @taberu.user_id ==current_user.id %>
               <td><%= link_to "Edit", edit_taberu_path(@taberu), class:"btn btn-success"%></td>
               <td><%= link_to "Destroy", taberu_path(@taberu), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger"%></td>
            <% end %>
           </tr>
          </tbody>
          </table>
       </div>
  </div>
</div>

app/views/users/_user_info.html.erb
<h2>User info</h2>
<% if user.profile_image.attached? %>
    <%= image_tag url_for(user.profile_image), size: "100x100" %>
  <% else %>
    <%= image_tag "no_image.jpg", size: "100x100" %>
<% end %>
<table class="table">
  <tbody>
    <tr>
      <th scope="row">name</th>
      <td>
        <%= user.name %>
      </td>
    </tr>
    <tr>
      <th scope="row">introduction</th>
      <td>
        <%= user.introduction %>
      </td>
    </tr>
  </tbody>
</table>

<% if user_signed_in? && user == current_user %>
  <div class="col mt-1">
<%= link_to user_path(@user.id), class: "btn btn-outline-danger btn-block",method: :delete do %>
    <p>退会</p>
    <% end %>
  </div>
<% end %>

<% if user_signed_in? && user == current_user %>
  <div class="col mt-2">
    <%= link_to edit_user_path(user), class: "btn btn-outline-dark btn-block" do %>
    <i class="fa-solid fa-user-gear"></i>

    <% end %>
  </div>
<% end %>

<h2 class="mt-3">New taberu</h2>
<%= form_with model: @taberu do |f| %>
  <div class="field">
    <!-- f.label :title 入力する事でcode内では小文字でもサイト上では大文字になる。-->
    <%= f.label :title %><br>
    <!--小さい文字入力出来るフィールドが出来る。-->
    <%= f.text_field :title %> 
  </div>
  <div class="field">
    <%= f.label :opinion %><br>
    <!--文字入力出来るフィールドが出来る。-->
    <%= f.text_area :body %>
  </div>
  <div class="row ml-0">
    <%= f.submit 'Create Taberu',  class: "btn btn-success"   %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container-fluid mt-5">
  <div class="header row">
    <div class="mx-auto">
      <div class="col">
        <h2>User info</h2>
      </div>

      <%= form_with model: @user do |f| %>
        <%= render "layouts/error", model: f.object %>

        <div class="row mt-1">
          <label for="inputName">Name</label>
        </div>
        <div class="row">
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
        </div>
        <div class="row mt-3">
          <label for="inputimage">Image</label>
        </div>
        <div class="row">
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>
        <div class="row mt-3">
          <label for="inputIntroduction">introduction</label>
        </div>
        <div class="row">
          <%= f.text_area :introduction %>
        </div>
        <div class="row mt-3">
          <%= f.submit "Update User" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
    <div class="col-md-3">
       <%= render 'taberus/taberu', taberus: @taberus,user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">

    <h1>Users</h1>
      <table class="table">
       <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
          <% @users.each do |user| %>
          <tr>
          <td>
            <%= image_tag user.get_profile_image(100,100) %>
            </td>
            <td><%= user.name %></td>
            
            <td>
                <%= link_to 'Show', user_path(user) %>
            </td>
          </tr>
          <% end %>
        </thead>
      </table>
    </div>
  </div>
</div>

<%= render 'taberus/footer' %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <!-- ユーザー情報や投稿フォームなど -->
    <div class="col-md-3">
      <%= render 'user_info', user: @user %>
    </div>

    <!-- 投稿一覧 -->
    <div class="col-md-8 offset-md-1">
      <h1>Taberus</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @taberus.each do |taberu| %>
            <tr>
              <td>
                <%= link_to user_path(taberu.user) do %>
                  <%= image_tag taberu.user.get_profile_image(100, 100) %>
                <% end %>
              </td>
              <td><%= link_to taberu.title, taberu_path(taberu) %></td>
              <td><%= taberu.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'taberus/footer' %>